name: native_sample
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Riverpod
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Lint
  flutter_lints: ^5.0.0
  custom_lint: ^0.7.1
  riverpod_lint: ^2.6.4

  # Generator
  build_runner: ^2.4.14
  riverpod_generator: ^2.6.4

flutter:
  uses-material-design: true
